/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        sisley: {
          black: '#000000',
          white: '#FFFFFF',
          bg: '#FAFAFA',
          surface: '#FFFFFF',
          border: '#E5E5E5',
          'border-strong': '#D4D4D4',
          muted: '#737373',
          'muted-strong': '#A3A3A3',
          text: '#171717',
          'text-secondary': '#525252',
          'text-tertiary': '#737373',
          dark: '#0a0a0a',
          'dark-surface': '#171717',
          'dark-muted': '#a3a3a3',
          ink: '#000000',
          paper: '#FFFFFF',
          charcoal: '#111111',
          smoke: '#F5F5F5',
          ash: '#E5E5E5',
          fog: '#FAFAFA',
        },
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        serif: ['var(--font-geist-serif)', 'Georgia', 'serif'],
      },
      fontSize: {
        'display-xl': ['8rem', { lineHeight: '0.9', letterSpacing: '-0.03em' }],
        'display-lg': ['6rem', { lineHeight: '0.95', letterSpacing: '-0.02em' }],
        'display-md': ['4.5rem', { lineHeight: '1', letterSpacing: '-0.02em' }],
        'display-sm': ['3.5rem', { lineHeight: '1.05', letterSpacing: '-0.01em' }],
        'editorial': ['clamp(3rem, 8vw, 7rem)', { lineHeight: '0.95', letterSpacing: '-0.02em' }],
        'headline': ['clamp(2rem, 5vw, 4.5rem)', { lineHeight: '1.05', letterSpacing: '-0.01em' }],
        'title-xl': ['clamp(1.5rem, 3vw, 2.5rem)', { lineHeight: '1.1', letterSpacing: '-0.01em' }],
        'title-lg': ['clamp(1.25rem, 2vw, 2rem)', { lineHeight: '1.15', letterSpacing: '-0.01em' }],
        'title-md': ['clamp(1.125rem, 1.5vw, 1.5rem)', { lineHeight: '1.2', letterSpacing: '-0.005em' }],
        'label': ['0.625rem', { lineHeight: '1.5', letterSpacing: '0.2em' }],
        'meta': ['0.6875rem', { lineHeight: '1.5', letterSpacing: '0.15em' }],
        'caption': ['0.75rem', { lineHeight: '1.5' }],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '30': '7.5rem',
        '36': '9rem',
        '42': '10.5rem',
        '48': '12rem',
      },
      borderRadius: {
        none: '0',
        sm: '2px',
        md: '4px',
        lg: '6px',
      },
      boxShadow: {
        none: '0 0 transparent',
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.04)',
        editorial: '0 0 0 1px rgba(0,0,0,0.03), 0 4px 20px rgba(0,0,0,0.04)',
        glow: '0 0 0 1px rgba(0,0,0,0.03), 0 8px 40px rgba(0,0,0,0.08)',
      },
      transitionDuration: {
        fast: '150ms',
        DEFAULT: '200ms',
        slow: '300ms',
        'slower': '500ms',
        editorial: '700ms',
        cinematic: '1000ms',
      },
      transitionTimingFunction: {
        DEFAULT: 'ease-out',
        editorial: 'cubic-bezier(0.16, 1, 0.3, 1)',
        cinematic: 'cubic-bezier(0.22, 1, 0.36, 1)',
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      aspectRatio: {
        'product': '3 / 4',
        'editorial': '4 / 5',
        'banner': '16 / 9',
        'portrait': '2 / 3',
        'landscape': '3 / 2',
        'ultrawide': '21 / 9',
        square: '1 / 1',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-down': {
          '0%': { opacity: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(1.05)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6' },
        },
        'slide-x': {
          '0%': { transform: 'scaleX(0)' },
          '100%': { transform: 'scaleX(1)' },
        },
        'slide-in-right': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'slide-out-right': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'reveal-up': {
          '0%': { opacity: '0', transform: 'translateY(40px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'reveal-scale': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'marquee': {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 700ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-out': 'fade-out 300ms ease-out forwards',
        'slide-up': 'slide-up 800ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-down': 'slide-down 600ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'scale-in': 'scale-in 1000ms cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'pulse-soft': 'pulse-soft 2ms ease-in-out',
        'slide-x': 'slide-x 300ms ease-out forwards',
        'slide-in-right': 'slide-in-right 500ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-out-right': 'slide-out-right 300ms ease-in forwards',
        'reveal-up': 'reveal-up 800ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'reveal-scale': 'reveal-scale 700ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'shimmer': 'shimmer 2s infinite linear',
        'marquee': 'marquee 30s linear infinite',
        'marquee-slow': 'marquee 45s linear infinite',
      },
    },
  },
  plugins: [],
}
